### ISSUE TITLE
be-stack.json file missing when building client

### ISSUE THREAD

**Issue by serverlessnomad** [OWASP/DVSA#10]
Looks like a json file is missing in the src directory.

ERROR in ./src/utils/apiCaller.js
Module not found: Error: Can't resolve '../be-stack.json' in '/Volumes/5TB/Code/DVSA/client/src/utils'
 @ ./src/utils/apiCaller.js 16:26-53
 @ ./src/components/StorePage.js
 @ ./src/routers/AppRouter.js
 @ ./src/app.js

ERROR in ./src/aws-exports.js
Module not found: Error: Can't resolve './be-stack.json' in '/Volumes/5TB/Code/DVSA/client/src'
 @ ./src/aws-exports.js 25:26-52
 @ ./src/app.js

**Comment by darkerego** [comment]
I have this issue too!

**Comment by 4ppsec** [comment]
Probably something went wrong. please try with new version.

Alternatively. You can deploy from our Serverless Repo page. See readme file
