### ISSUE TITLE
npm i , Error with node version 8 (working with version 10)

### ISSUE THREAD

**Issue by DavidCervigni** [OWASP/DVSA#13]
npm ERR! Linux 4.15.0-45-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2

npm ERR! Invalid Package: expected serverless-plugin-protego-fsp but found serverless-protego-plugin
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/david/workspace/DVSA/backend/src/functions/order-api/npm-debug.log

npm ERR! Linux 4.15.0-45-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! dvsa@1.0.0 postinstall: `cd client && npm i && cd ../backend/src/functions/order-api && npm i`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dvsa@1.0.0 postinstall script 'cd client && npm i && cd ../backend/src/functions/order-api && npm i'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dvsa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd client && npm i && cd ../backend/src/functions/order-api && npm i
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dvsa
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dvsa
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/david/workspace/DVSA/npm-debug.log

**Comment by 4ppsec** [comment]
Please remove
`"devDependencies": {
    "serverless-plugin-protego-fsp": "https://artifactory.app.protego.io/protego-serverless-plugin.tgz"
  },`


from backend/src/functions/order-api/package.json

or clone a new version.
