### ISSUE TITLE
packaging freezes for long time

### ISSUE THREAD

**Issue by DavidCervigni** [OWASP/DVSA#14]
I have experienced this with two different linux distro (ubuntu and centos) and on mac os as well:
The issue looks similar to:
https://github.com/serverless/serverless/issues/3882
sometimes it works after more than say 15 minutes hanging...

david@ubuntu:~/workspace/DVSA$ sls deploy
Running command: python backend/serverless/scripts/onstart.py
############################################################################
#                                                                          #
#                    ██████╗ ██╗   ██╗███████╗ █████╗                      #
#                    ██╔══██╗██║   ██║██╔════╝██╔══██╗                     #
#                    ██║  ██║██║   ██║███████╗███████║                     #
#                    ██║  ██║╚██╗ ██╔╝╚════██║██╔══██║                     #
#                    ██████╔╝ ╚████╔╝ ███████║██║  ██║                     #
#                    ╚═════╝   ╚═══╝  ╚══════╝╚═╝  ╚═╝                     #
#                                                                          #
#     You are deploying DVSA: a Damn vulnerable Serverless Application     #
#  This project was donated to OWASP by Protego Labs (https://protego.io)  #
#  Make sure you read all the necessary information on the project page:   #
#  https://github.com/owasp/dvsa | online version: http://serverless.fail  #
#                                                                          #
############################################################################

Serverless: Packaging service...

**Comment by 4ppsec** [comment]
I removed support for Serverless framework. It was too complicated to maintain two different IaC.
The deployment is done using AWS SAM now.
