### ISSUE TITLE
When I deploy backend，I got the error “The CloudFormation template is invalid...."

### ISSUE THREAD

**Issue by AshinTop** [OWASP/DVSA#17]
When I deploy backend,I get the error "The CloudFormation template is invalid: Template format error: Unrecognized resource types: [AWS::Cognito::UserPool, AWS::Cognito::IdentityPoolRoleAttachment, AWS::Cognito::UserPoolClient, AWS::Cognito::IdentityPool]".

The error part is following:
![image](https://user-images.githubusercontent.com/45983426/63570769-d29e0c80-c5b0-11e9-87b9-e4e7c6beba69.png)

My region is cn-north-1.It is my first time to use aws cli to build a application in Lambda.I don't know where is wrong.

My serverless.yml different is following:
![image](https://user-images.githubusercontent.com/45983426/63570853-0ed16d00-c5b1-11e9-974d-66c9f39b7d8c.png)

**Comment by 4ppsec** [comment]
Please try with new version.
