### ISSUE TITLE
Cannot deploy Serverless Repo to AWS lambda

### ISSUE THREAD

**Issue by halfluke** [OWASP/DVSA#20]
I think the issue has to do with this:

The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: ..................)

https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

https://aws.amazon.com/blogs/compute/node-js-12-x-runtime-now-available-in-aws-lambda/

Any chance this can be fixed?

**Comment by 4ppsec** [comment]
will be fixed soon.

**Comment by 4ppsec** [comment]
Fixed. 

DVSA now uses node12.x and python3.6.
