### ISSUE TITLE
AWS Deploy Error

### ISSUE THREAD

**Issue by pradeepjairamani** [OWASP/DVSA#25]
Hello,

When I am trying to install DVSA  on AWS from the repository:
https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:889485553959:applications~DVSA

The InitializeApplication function is taking a lot of time and the request fails, this results in a rollback of the complete application.
I have tried doing this with 3 different accounts and have failed to deploy the  serverless application.

**Comment by pradeepjairamani** [comment]
![dvsa](https://user-images.githubusercontent.com/24669027/83835124-92f27c80-a70d-11ea-8794-69e31eca6212.png)

A Screenshot has been shared of the event logs

**Comment by 4ppsec** [comment]
@pradeepjairamani - sorry for the delay.
I could not reproduce it. Were you able to reproduce/fix?
