### ISSUE TITLE
after deploy i got link but link is not working imnot getting how to change permissions 

### ISSUE THREAD

**Issue by hackersden09** [OWASP/DVSA#26]
http://dvsa-website-686121694555.s3-website-us-east-2.amazonaws.com/

**Hmm. We’re having trouble finding that site.**

**Comment by amit-schnitzer** [comment]
seems like a typo with your URL
use the below instead 
http://dvsa-website-686121694555.s3-website.us-east-2.amazonaws.com/

I have changed the "-" sign with "." before the "us" and that did the trick

**Comment by 4ppsec** [comment]
fixed
