### ISSUE TITLE
Attach File is not working in Feedback Information

### ISSUE THREAD

**Issue by fernandostc** [OWASP/DVSA#32]
When you try to create feedback and attach the file is not being uploaded to the feedback S3 bucket
The fix still not working. It still failing

Failed to load resource: the server responded with a status of 405 (Method Not Allowed)
Looks like there is error here: Uncaught (in promise) TypeError: Cannot read property 'key' of undefined at bundle.js:308

**Comment by 4ppsec** [comment]
I will be releasing a new version soon and this will be fixed.

**Comment by 4ppsec** [comment]
fixed
