### ISSUE TITLE
Step by step guide - "npm i" fails with error

### ISSUE THREAD

**Issue by nikhilenmudi** [OWASP/DVSA#39]
npm ERR!                                                                herror
npm ERR! make: *** [Release/obj.target/binding/src/binding.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/ec2-user/environment/dvsa-repo/client/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Linux 4.14.296-222.539.amzn2.x86_64
npm ERR! gyp ERR! command "/home/ec2-user/.nvm/versions/node/v16.18.1/bin/node" "/home/ec2-user/environment/dvsa-repo/client/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/ec2-user/environment/dvsa-repo/client/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.18.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2022-12-10T22_03_04_213Z-debug-0.log
npm ERR! code 1
npm ERR! path /home/ec2-user/environment/dvsa-repo
npm ERR! command failed
npm ERR! command sh -c -- cd client && npm i && cd ../backend/src/functions/order-api && npm i

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2022-12-10T22_02_55_450Z-debug-0.log

**Comment by 4ppsec** [comment]
At the moment client is only compiled with:
* Node 8.2.16
* Python2.7
I updated the documentation of how to run that. Please take a look at the [README](https://github.com/OWASP/DVSA/blob/master/README.md) file.
